apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/yarin182/ArgoCD-EKS-Test.git
    targetRevision: HEAD
    path: argocd/prometheus
    directory:
      include: prometheus-gateway.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 