apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true, Wait=true
spec:
  project: default
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    chart: gateway
    targetRevision: 1.26.2
    helm:
      values: |
        name: istio-ingressgateway
        labels:
          istio: ingressgateway
        service:
          type: ClusterIP   # ✅ Changed from LoadBalancer to ClusterIP
        podAnnotations:
          sidecar.istio.io/inject: "false"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
