apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
spec:
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.22.0
    helm:
      values: |
        name: istio-ingressgateway
        labels:
          istio: ingressgateway
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
