apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  annotations:
    # Ensure Istio ingress runs only after Istiod is ready
    argocd.argoproj.io/sync-wave: "2"
    # Allow ArgoCD to skip dry-run when Istio CRDs aren't ready yet
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    # Enforce wait behavior for readiness
    argocd.argoproj.io/sync-options: Wait=true
spec:
  project: default
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    chart: gateway
    targetRevision: 1.26.2
    helm:
      values: |
        name: istio-ingressgateway
        labels:
          istio: ingressgateway
        service:
          type: LoadBalancer
        podAnnotations:
          sidecar.istio.io/inject: "false"  # Prevent sidecar injection
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true   # Avoid unnecessary re-applies
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
