apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd2
    targetRevision: 2.11.5
    helm:
      values: |
        global:
          clusterNetworks: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        # Let Linkerd generate its own certificates
        proxy:
          inboundPort: 4143
          outboundPort: 4140
          adminPort: 4191
          controlPort: 4190
          resource:
            request:
              cpu: 10m
              memory: 20Mi
            limit:
              cpu: 100m
              memory: 100Mi
        proxyInit:
          resource:
            request:
              cpu: 10m
              memory: 10Mi
            limit:
              cpu: 100m
              memory: 50Mi
        proxy:
          resources:
            cpu:
              request: 100m
              limit: 200m
            memory:
              request: 128Mi
              limit: 256Mi
        proxyInit:
          resources:
            cpu:
              request: 100m
              limit: 200m
            memory:
              request: 128Mi
              limit: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true 