apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd2
    targetRevision: 2.11.5
    helm:
      values: |
        # Minimal configuration for linkerd2 chart
        global:
          clusterNetworks: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        # Basic proxy configuration
        proxy:
          resources:
            cpu:
              request: 100m
              limit: 200m
            memory:
              request: 128Mi
              limit: 256Mi
        proxyInit:
          resources:
            cpu:
              request: 100m
              limit: 200m
            memory:
              request: 128Mi
              limit: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true 