apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiali-ingress
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
    traefik.ingress.kubernetes.io/router.middlewares: "istio-system-kiali-stripprefix@kubernetescrd"
spec:
  rules:
  - http:
      paths:
      - path: /kiali
        pathType: Prefix
        backend:
          service:
            name: kiali
            port:
              number: 20001
      - path: /kiali/
        pathType: Prefix
        backend:
          service:
            name: kiali
            port:
              number: 20001
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: kiali-stripprefix
  namespace: istio-system
spec:
  stripPrefix:
    prefixes:
    - /kiali
    - /kiali/ 